global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: ${SMTP_USERNAME}
  smtp_auth_username: ${SMTP_USERNAME}
  smtp_auth_password: ${SMTP_PASSWORD}
  smtp_require_tls: true

route:
  receiver: "email-alert"

receivers:
  - name: "email-alert"
    email_configs:
      - to: ${SMTP_USERNAME}
        send_resolved: true
