global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "yourname@gmail.com"
  smtp_auth_username: "yourname@gmail.com"
  smtp_auth_password: "your_app_password"
  smtp_require_tls: true

route:
  receiver: "email-alert"

receivers:
  - name: "email-alert"
    email_configs:
      - to: "yourname@gmail.com"
        send_resolved: true
