global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "mongo-exporter"
    static_configs:
      - targets: ["mongo-exporter:9216"]

  - job_name: "your-backend"
    static_configs:
      - targets: ["backend:3000"]
